version: '3.8'

services:
  chat_db:
    image: postgres:16
    container_name: chat_postgres
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - ./data/chat:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  moderation_db:
    image: postgres:16
    container_name: moderation_postgres
    environment:
      POSTGRES_USER: moderation
      POSTGRES_PASSWORD: moderationpass
      POSTGRES_DB: moderation
    ports:
      - "5433:5432"
    volumes:
      - ./data/moderation:/var/lib/postgresql/data

  logs_db:
    image: postgres:16
    container_name: logs_db
    environment:
      POSTGRES_USER: logs
      POSTGRES_PASSWORD: logspass
      POSTGRES_DB: logs
    ports:
      - "5434:5432"
    volumes:
      - ./data/logs:/var/lib/postgresql/data

  keycloak_db:
    image: postgres:16
    container_name: keycloak_postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keypass
      POSTGRES_DB: keycloakdb
    ports:
      - "5435:5432"
    volumes:
      - ./data/keycloak:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: my_keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keypass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak_db

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"   
      - "5672:5672"  
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
