version: '3.8'

services:
  chat_db:
    image: postgres:16
    container_name: chat_postgres
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chat
    ports:
      - '5432:5432'
    volumes:
      - ./data/chat:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  chat:
    build: .
    image: brunoespindoladev/chat:latest
    ports:
      - '5000:5000'
    depends_on:
      - chat_db
